---
- name: Install nginx
  apt: name=nginx

- name: Clone drupal.conf from repository
  git: repo=https://github.com/jackbravo/simple-drupal-nginx.git dest=/etc/nginx/simple-drupal-nginx/

- name: Create sites-available configurations
  template: src=default.conf dest=/etc/nginx/sites-available/{{ item.key }}
  with_dict: sites
  notify: restart nginx

- name: Link sites-enabled configurations
  file: src=/etc/nginx/sites-available/{{ item.key }} dest=/etc/nginx/sites-enabled/{{ item.key }} state=link
  with_dict: sites
  notify: restart nginx
