---
- name: Install Common packages
  apt: name={{ item }}
  with_items:
    - fish
    - git
    - tig
    - htop
    - iotop
    - fail2ban
    - curl
    - vim
  when: ansible_os_family == 'Debian'

- name: Install Common packages
  yum: name={{ item }}
  with_items:
    - epel-release
    - git
    - tig
    - htop
    - iotop
    - fail2ban
    - curl
    - vim
    - byobu
  when: ansible_os_family == 'RedHat'

- name: set up .tmux.conf for user
  get_url: url=https://gist.githubusercontent.com/jackbravo/7163635/raw/81d353fe42397d907edb9b6a532a8345552fba73/.tmux.conf dest=~/.tmux.conf
  sudo: no
  when: ansible_os_family == 'RedHat'

- name: Install fish
  yum: name=http://fishshell.com/files/2.1.0/linux/RedHat_RHEL-6/fish-2.1.0-2.1.x86_64.rpm
  when: ansible_os_family == 'RedHat'

- name: set the shell as fish for user
  user: name={{ ansible_ssh_user }} shell=/usr/bin/fish

- name: set up .vimrc for root
  get_url: url=https://gist.githubusercontent.com/jackbravo/7163461/raw/7278d317e82ce55bbe676bf8f891a30af524b9b6/.vimrc dest=/root/.vimrc

- name: set up .vimrc for user
  get_url: url=https://gist.githubusercontent.com/jackbravo/7163461/raw/7278d317e82ce55bbe676bf8f891a30af524b9b6/.vimrc dest=~/.vimrc
  sudo: no
