---
- name: Install Composer
  shell:
    curl -sS https://getcomposer.org/installer | php && mv composer.phar /usr/local/bin/composer
    creates=/usr/local/bin/composer

- name: Add global composer bin directory to PATH
  lineinfile: dest=~/.bashrc line="export PATH=~/.composer/vendor/bin:$PATH"

- name: Install drush
  shell: composer global require drush/drush:dev-master --no-interaction --no-ansi
