---
- name: make sure the vhosts directory exists
  file: path=/var/www/vhosts/{{ item.key }} state=directory mode=2775 group=users
  with_dict: sites

- name: Copy the code from repository
  git: repo={{ item.value.git }} dest=/var/www/vhosts/{{ item.key }}/drupal version={{ item.value.version }}
  with_dict: sites

- name: Create files path
  file: path=/var/www/vhosts/{{ item.key }}/drupal/sites/default/files state=directory mode=2775 group=www-data recurse=yes
  with_dict: sites
