---
- name: make sure the ssh user is part of users
  user: name={{ ansible_ssh_user }} groups=www-data,users append=yes
  when: ansible_ssh_user != 'root'
  
- name: make sure the vhosts directory exists
  file: path=/var/www/vhosts/{{ item.key }} state=directory mode=2775 group=users
  with_dict: sites

- name: Clone the code from repository
  git: repo={{ item.value.git }} dest=/var/www/vhosts/{{ item.key }}/drupal version={{ item.value.version }} accept_hostkey=yes
  with_dict: sites
  sudo: no

- name: Create files path
  file: path=/var/www/vhosts/{{ item.key }}/drupal/sites/default/files state=directory mode=2775 owner={{ ansible_ssh_user }} group=www-data recurse=yes
  with_dict: sites

- name: Copy default.settings.php file
  shell: cp /var/www/vhosts/{{ item.key }}/drupal/sites/default/default.settings.php /var/www/vhosts/{{ item.key }}/drupal/sites/default/settings.php && chgrp www-data /var/www/vhosts/{{ item.key }}/drupal/sites/default/settings.php
    creates=/var/www/vhosts/{{ item.key }}/drupal/sites/default/settings.php
  with_dict: sites
  sudo: no

- name: Copy default.services.yml file (ignores errors for non D8 sites)
  shell: cp /var/www/vhosts/{{ item.key }}/drupal/sites/default/default.services.yml /var/www/vhosts/{{ item.key }}/drupal/sites/default/services.yml && chgrp www-data /var/www/vhosts/{{ item.key }}/drupal/sites/default/services.yml
    creates=/var/www/vhosts/{{ item.key }}/drupal/sites/default/services.yml
  with_dict: sites
  sudo: no
  ignore_errors: true
